import type { Product, Category, PromoSlide, FAQ } from './types'

export const CATEGORIES: Category[] = [
  { id: '1',  name: 'Тетради и дневники',        slug: 'notebooks',        emoji: '📓', count: 248, color: '#2B4DD6', iconBg: '#EEF2FF' },
  { id: '2',  name: 'Ручки и карандаши',          slug: 'pens-pencils',      emoji: '🖊️', count: 512, color: '#FF8A3D', iconBg: '#FFF4EC' },
  { id: '3',  name: 'Краски и кисти',             slug: 'paints-brushes',    emoji: '🎨', count: 184, color: '#7DD3C0', iconBg: '#EDFAF7' },
  { id: '4',  name: 'Бумага и альбомы',           slug: 'paper-albums',      emoji: '📄', count: 133, color: '#22c55e', iconBg: '#F0FDF4' },
  { id: '5',  name: 'Папки и архив',              slug: 'folders',           emoji: '📁', count: 97,  color: '#f59e0b', iconBg: '#FFFBEB' },
  { id: '6',  name: 'Клей и ножницы',             slug: 'glue-scissors',     emoji: '✂️', count: 76,  color: '#ef4444', iconBg: '#FEF2F2' },
  { id: '7',  name: 'Линейки и циркули',          slug: 'rulers-compasses',  emoji: '📏', count: 64,  color: '#2B4DD6', iconBg: '#EEF2FF' },
  { id: '8',  name: 'Ежедневники',                slug: 'planners',          emoji: '📅', count: 89,  color: '#FF8A3D', iconBg: '#FFF4EC' },
  { id: '9',  name: 'Рюкзаки и пеналы',          slug: 'bags-pencilcases',  emoji: '🎒', count: 152, color: '#7DD3C0', iconBg: '#EDFAF7' },
  { id: '10', name: 'Хобби и творчество',         slug: 'hobbies-art',       emoji: '🧶', count: 341, color: '#8b5cf6', iconBg: '#F5F3FF' },
  { id: '11', name: 'Техника и картриджи',        slug: 'tech-cartridges',   emoji: '🖨️', count: 218, color: '#0ea5e9', iconBg: '#F0F9FF' },
  { id: '12', name: 'Подарки и сувениры',         slug: 'gifts-souvenirs',   emoji: '🎁', count: 127, color: '#FF8A3D', iconBg: '#FFF4EC' },
]

export const PRODUCTS: Product[] = [
  /* ── Тетради ── */
  {
    id: '1',
    name: 'Тетрадь школьная А5, 24 листа «Однотонная серия»',
    slug: 'tetrad-a5-24-hatber',
    price: 0.93,
    brand: 'Hatber',
    sku: 'TS-24-A5-G',
    categoryId: '1',
    categoryName: 'Тетради и дневники',
    images: ['/images/placeholder-product.svg'],
    rating: 4.8,
    reviewCount: 124,
    stock: 1248,
    badges: ['hit'],
    description: 'Классическая школьная тетрадь в клетку для учеников начальных и средних классов. Плотная белая бумага не просвечивает, гладкая поверхность подходит для письма любой ручкой — шариковой, гелевой и капиллярной.',
    specs: { 'Формат': 'А5 (165×200 мм)', 'Листов': '24', 'Разлиновка': 'Клетка', 'Крепление': 'Скоба', 'Плотность': '60 г/м²', 'Страна': 'Беларусь' },
  },
  {
    id: '9',
    name: 'Тетрадь общая А4, 96 листов, клетка',
    slug: 'tetrad-a4-96-hatber',
    price: 2.45,
    brand: 'Hatber',
    sku: 'TS-96-A4-K',
    categoryId: '1',
    categoryName: 'Тетради и дневники',
    images: ['/images/placeholder-product.svg'],
    rating: 4.7,
    reviewCount: 88,
    stock: 512,
    badges: [],
    description: 'Общая тетрадь формата А4 в клетку на скрепке. Подходит для конспектов, учёбы и работы.',
    specs: { 'Формат': 'А4', 'Листов': '96', 'Разлиновка': 'Клетка', 'Крепление': 'Скоба', 'Плотность': '60 г/м²' },
  },
  {
    id: '10',
    name: 'Дневник школьный твёрдая обложка А5, 48 листов',
    slug: 'diary-school-a5-48',
    price: 3.20,
    oldPrice: 4.50,
    brand: 'МЗБА',
    sku: 'DL-A5-48-HC',
    categoryId: '1',
    categoryName: 'Тетради и дневники',
    images: ['/images/placeholder-product.svg'],
    rating: 4.5,
    reviewCount: 64,
    stock: 320,
    badges: ['sale'],
    description: 'Школьный дневник А5 на весь учебный год. Твёрдая обложка, качественная офсетная бумага.',
    specs: { 'Формат': 'А5', 'Листов': '48', 'Обложка': 'Твёрдая', 'Страна': 'Беларусь' },
  },

  /* ── Ручки и карандаши ── */
  {
    id: '2',
    name: 'Ручка шариковая автоматическая Schneider Tops 505 F',
    slug: 'schneider-tops-505-f',
    price: 1.22,
    brand: 'Schneider',
    sku: 'SCH-505-F-BL',
    categoryId: '2',
    categoryName: 'Ручки и карандаши',
    images: ['/images/placeholder-product.svg'],
    rating: 4.9,
    reviewCount: 87,
    stock: 340,
    badges: ['bestseller'],
    description: 'Лёгкая и надёжная автоматическая ручка немецкого производства с ergo-формой корпуса. Документальные чернила не выцветают и подходят для подписи официальных бумаг.',
    specs: { 'Тип': 'Автоматическая шариковая', 'Толщина линии': '0,5 мм (F)', 'Цвет чернил': 'Синий', 'Длина письма': 'до 1 800 м', 'Гарантия': '12 месяцев' },
  },
  {
    id: '6',
    name: 'Ручка гелевая BRAUBERG Soft Touch, 0.5 мм',
    slug: 'brauberg-gel-soft-touch',
    price: 0.85,
    oldPrice: 1.20,
    brand: 'BRAUBERG',
    sku: 'BB-GEL-05-BL',
    categoryId: '2',
    categoryName: 'Ручки и карандаши',
    images: ['/images/placeholder-product.svg'],
    rating: 4.7,
    reviewCount: 203,
    stock: 892,
    badges: ['sale', 'hit'],
    description: 'Гелевая ручка с мягким резиновым грипом. Чернила насыщенного синего цвета, не размазываются. Идеальна для ежедневного письма.',
    specs: { 'Тип': 'Гелевая', 'Толщина линии': '0,35 мм', 'Цвет чернил': 'Синий', 'Грип': 'Резиновый' },
  },
  {
    id: '11',
    name: 'Ручка капиллярная Pilot Fineliner SW-PPF, 0.4 мм',
    slug: 'pilot-fineliner-0-4',
    price: 1.85,
    brand: 'Pilot',
    sku: 'PLT-FIN-04-BL',
    categoryId: '2',
    categoryName: 'Ручки и карандаши',
    images: ['/images/placeholder-product.svg'],
    rating: 4.8,
    reviewCount: 145,
    stock: 280,
    badges: ['new'],
    description: 'Капиллярная ручка с тонким металлическим кончиком для точного и чёткого письма. Подходит для черчения и технических рисунков.',
    specs: { 'Тип': 'Капиллярная', 'Толщина линии': '0,4 мм', 'Цвет чернил': 'Синий', 'Наконечник': 'Металл' },
  },
  {
    id: '12',
    name: 'Ручка гелевая ErichKrause G-Soft, 0.38 мм, синяя',
    slug: 'erichkrause-g-soft-0-38',
    price: 0.72,
    brand: 'ErichKrause',
    sku: 'EK-GS-038-BL',
    categoryId: '2',
    categoryName: 'Ручки и карандаши',
    images: ['/images/placeholder-product.svg'],
    rating: 4.6,
    reviewCount: 312,
    stock: 1540,
    badges: ['hit'],
    description: 'Ультратонкая гелевая ручка с мягким пишущим узлом. Быстро сохнущие чернила, не оставляет клякс.',
    specs: { 'Тип': 'Гелевая', 'Толщина линии': '0,38 мм', 'Цвет чернил': 'Синий' },
  },
  {
    id: '3',
    name: 'Набор карандашей цветных «Енот в Испании», 12 цветов',
    slug: 'pencils-enot-12',
    price: 3.98,
    brand: 'Раскраски-Енот',
    sku: 'KZ-RC-12',
    categoryId: '2',
    categoryName: 'Ручки и карандаши',
    images: ['/images/placeholder-product.svg'],
    rating: 4.7,
    reviewCount: 56,
    stock: 215,
    badges: ['new'],
    description: 'Яркие, мягкие цветные карандаши для маленьких художников и школьников. Легко затачиваются, не крошатся.',
    specs: { 'Цветов': '12', 'Длина': '175 мм', 'Грифель': '3,0 мм', 'Форма': 'Шестигранная', 'Возраст': '3+' },
  },
  {
    id: '13',
    name: 'Маркер для доски BRAUBERG, смываемый, синий',
    slug: 'brauberg-whiteboard-marker',
    price: 1.10,
    oldPrice: 1.50,
    brand: 'BRAUBERG',
    sku: 'BB-MRK-WB-BL',
    categoryId: '2',
    categoryName: 'Ручки и карандаши',
    images: ['/images/placeholder-product.svg'],
    rating: 4.4,
    reviewCount: 91,
    stock: 455,
    badges: ['sale'],
    description: 'Смываемый маркер для белых досок с круглым наконечником. Легко стирается любой влажной губкой.',
    specs: { 'Тип': 'Для доски', 'Наконечник': 'Круглый 3 мм', 'Цвет': 'Синий', 'Смываемость': 'Да' },
  },

  /* ── Краски и кисти ── */
  {
    id: '4',
    name: 'Краски акварельные «Енот в Красном море», 6 цветов',
    slug: 'watercolor-enot-6',
    price: 2.13,
    brand: 'Раскраски-Енот',
    sku: 'AK-RC-6',
    categoryId: '3',
    categoryName: 'Краски и кисти',
    images: ['/images/placeholder-product.svg'],
    rating: 4.6,
    reviewCount: 42,
    stock: 178,
    badges: [],
    description: 'Классическая медовая акварель для детского творчества с безопасным натуральным составом.',
    specs: { 'Тип': 'Акварель медовая', 'Цветов': '6', 'Состав': 'Натуральный пигмент, мёд', 'Возраст': '3+' },
  },
  {
    id: '14',
    name: 'Краски гуашь 12 цветов, 20 мл, «Луч»',
    slug: 'gouache-luch-12',
    price: 4.90,
    oldPrice: 6.20,
    brand: 'Луч',
    sku: 'LCH-GUA-12-20',
    categoryId: '3',
    categoryName: 'Краски и кисти',
    images: ['/images/placeholder-product.svg'],
    rating: 4.7,
    reviewCount: 78,
    stock: 234,
    badges: ['sale'],
    description: 'Насыщенная гуашевая краска в баночках для художественного творчества. Хорошо перекрывает предыдущие слои.',
    specs: { 'Цветов': '12', 'Объём': '20 мл/баночка', 'Тип': 'Гуашь', 'Возраст': '6+' },
  },
  {
    id: '15',
    name: 'Кисть художественная пони «Сонет» №8, круглая',
    slug: 'brush-sonet-pony-8',
    price: 2.30,
    brand: 'Сонет',
    sku: 'SNT-BR-P8-RD',
    categoryId: '3',
    categoryName: 'Краски и кисти',
    images: ['/images/placeholder-product.svg'],
    rating: 4.5,
    reviewCount: 33,
    stock: 187,
    badges: [],
    description: 'Мягкая круглая кисть из ворса пони. Хорошо держит форму, подходит для акварели и гуаши.',
    specs: { 'Номер': '8', 'Форма': 'Круглая', 'Ворс': 'Пони', 'Ручка': 'Деревянная лакированная' },
  },

  /* ── Бумага и альбомы ── */
  {
    id: '16',
    name: 'Альбом для рисования А4, 24 листа, Hatber',
    slug: 'album-drawing-a4-24',
    price: 1.85,
    brand: 'Hatber',
    sku: 'ALB-A4-24-HT',
    categoryId: '4',
    categoryName: 'Бумага и альбомы',
    images: ['/images/placeholder-product.svg'],
    rating: 4.6,
    reviewCount: 55,
    stock: 634,
    badges: ['hit'],
    description: 'Альбом для рисования с плотной бумагой 100 г/м². Подходит для карандашей, фломастеров и акварели.',
    specs: { 'Формат': 'А4', 'Листов': '24', 'Плотность': '100 г/м²', 'Крепление': 'Клееный блок' },
  },
  {
    id: '17',
    name: 'Бумага цветная А4, 10 цветов, 20 листов, Hatber',
    slug: 'paper-colored-a4-20',
    price: 1.20,
    brand: 'Hatber',
    sku: 'PPC-A4-20-HT',
    categoryId: '4',
    categoryName: 'Бумага и альбомы',
    images: ['/images/placeholder-product.svg'],
    rating: 4.4,
    reviewCount: 47,
    stock: 895,
    badges: [],
    description: 'Яркая цветная бумага для творчества, аппликаций и поделок. 10 двусторонних насыщенных цветов.',
    specs: { 'Формат': 'А4', 'Листов': '20', 'Цветов': '10', 'Плотность': '80 г/м²' },
  },

  /* ── Папки и архив ── */
  {
    id: '7',
    name: 'Папка-скоросшиватель ErichKrause, A4',
    slug: 'folder-erichkrause-a4',
    price: 1.15,
    brand: 'ErichKrause',
    sku: 'EK-FOLD-A4-BL',
    categoryId: '5',
    categoryName: 'Папки и архив',
    images: ['/images/placeholder-product.svg'],
    rating: 4.5,
    reviewCount: 67,
    stock: 423,
    badges: [],
    description: 'Пластиковая папка-скоросшиватель с перфорацией для удобного хранения документов формата А4.',
    specs: { 'Формат': 'A4', 'Материал': 'Полипропилен 0,15 мм', 'Цвет': 'Синий' },
  },

  /* ── Клей и ножницы ── */
  {
    id: '18',
    name: 'Ножницы офисные ErichKrause, 17 см, нержавейка',
    slug: 'scissors-erichkrause-17',
    price: 2.80,
    brand: 'ErichKrause',
    sku: 'EK-SCS-17-SS',
    categoryId: '6',
    categoryName: 'Клей и ножницы',
    images: ['/images/placeholder-product.svg'],
    rating: 4.7,
    reviewCount: 108,
    stock: 312,
    badges: ['hit'],
    description: 'Офисные ножницы с нержавеющими лезвиями и удобными прорезиненными ручками. Острые и долговечные.',
    specs: { 'Длина': '17 см', 'Лезвие': 'Нержавеющая сталь', 'Ручки': 'Прорезиненные' },
  },
  {
    id: '19',
    name: 'Клей-карандаш BRAUBERG Economy, 15 г',
    slug: 'glue-stick-brauberg-15g',
    price: 0.65,
    brand: 'BRAUBERG',
    sku: 'BB-GLU-15-EC',
    categoryId: '6',
    categoryName: 'Клей и ножницы',
    images: ['/images/placeholder-product.svg'],
    rating: 4.3,
    reviewCount: 219,
    stock: 2140,
    badges: [],
    description: 'Экономичный клей-карандаш для склеивания бумаги, картона, фотографий. Не оставляет следов.',
    specs: { 'Объём': '15 г', 'Тип': 'ПВА-основа', 'Применение': 'Бумага, картон, фото' },
  },

  /* ── Линейки ── */
  {
    id: '20',
    name: 'Линейка пластиковая 30 см, прозрачная, Стамм',
    slug: 'ruler-stamm-30',
    price: 0.45,
    brand: 'Стамм',
    sku: 'STM-RUL-30-TR',
    categoryId: '7',
    categoryName: 'Линейки и циркули',
    images: ['/images/placeholder-product.svg'],
    rating: 4.4,
    reviewCount: 176,
    stock: 1820,
    badges: ['hit'],
    description: 'Прозрачная пластиковая линейка 30 см с чёткой миллиметровой шкалой. Класс точности — 2.',
    specs: { 'Длина': '30 см', 'Материал': 'Прозрачный пластик', 'Шкала': 'Миллиметровая' },
  },

  /* ── Ежедневники ── */
  {
    id: '5',
    name: 'Ежедневник датированный на 2026 год BG, 168 листов',
    slug: 'planner-bg-2026',
    price: 5.00,
    oldPrice: 9.05,
    brand: 'BG',
    sku: 'BG-DAY-2026-GRN',
    categoryId: '8',
    categoryName: 'Ежедневники',
    images: ['/images/placeholder-product.svg'],
    rating: 4.8,
    reviewCount: 31,
    stock: 89,
    badges: ['sale'],
    description: 'Стильный датированный ежедневник на 2026 год с мягкой обложкой из кожзама. Закладка-ляссе, адресная и телефонная книжка.',
    specs: { 'Год': '2026', 'Формат': 'A5 (135×205 мм)', 'Листов': '168', 'Бумага': '70 г/м²', 'Обложка': 'Иск. кожа' },
  },
  {
    id: '24',
    name: 'Блокнот А6, 80 листов в клетку, ErichKrause',
    slug: 'notebook-a6-80-ek',
    price: 2.10,
    brand: 'ErichKrause',
    sku: 'EK-NB-A6-80-K',
    categoryId: '8',
    categoryName: 'Ежедневники',
    images: ['/images/placeholder-product.svg'],
    rating: 4.5,
    reviewCount: 62,
    stock: 430,
    badges: ['new'],
    description: 'Компактный блокнот А6 в клетку на кольцах. Удобен для заметок, встреч и списков дел.',
    specs: { 'Формат': 'А6', 'Листов': '80', 'Разлиновка': 'Клетка', 'Крепление': 'Кольца' },
  },

  /* ── Рюкзаки и пеналы ── */
  {
    id: '8',
    name: 'Рюкзак школьный Koh-I-Noor «Лесные звери», 20 л',
    slug: 'backpack-koh-i-noor-forest',
    price: 24.90,
    oldPrice: 34.50,
    brand: 'Koh-I-Noor',
    sku: 'KN-BP-FOREST-20',
    categoryId: '9',
    categoryName: 'Рюкзаки и пеналы',
    images: ['/images/placeholder-product.svg'],
    rating: 4.9,
    reviewCount: 89,
    stock: 32,
    badges: ['sale', 'hit'],
    description: 'Ортопедический школьный рюкзак с анатомической спинкой и ярким принтом.',
    specs: { 'Объём': '20 л', 'Вес': '0,85 кг', 'Спинка': 'Анатомическая', 'Материал': 'Полиэстер 600D' },
  },
  {
    id: '21',
    name: 'Пенал школьный на молнии ErichKrause, двойной',
    slug: 'pencilcase-ek-double',
    price: 5.50,
    oldPrice: 7.20,
    brand: 'ErichKrause',
    sku: 'EK-PC-DBL-BL',
    categoryId: '9',
    categoryName: 'Рюкзаки и пеналы',
    images: ['/images/placeholder-product.svg'],
    rating: 4.6,
    reviewCount: 74,
    stock: 158,
    badges: ['sale'],
    description: 'Двойной пенал на молнии с мягкой текстурной поверхностью. Вмещает 2 полных комплекта канцтоваров.',
    specs: { 'Тип': 'Двойной', 'Застёжка': 'Молния', 'Материал': 'Полиэстер' },
  },

  /* ── Хобби ── */
  {
    id: '22',
    name: 'Пластилин «Луч» 12 цветов, 240 г',
    slug: 'plasticine-luch-12',
    price: 3.60,
    brand: 'Луч',
    sku: 'LCH-PLS-12-240',
    categoryId: '10',
    categoryName: 'Хобби и творчество',
    images: ['/images/placeholder-product.svg'],
    rating: 4.8,
    reviewCount: 113,
    stock: 467,
    badges: ['hit'],
    description: 'Мягкий, хорошо лепящийся пластилин в ярких насыщенных цветах. Не прилипает к рукам.',
    specs: { 'Цветов': '12', 'Масса': '240 г', 'Тип': 'Классический', 'Возраст': '3+' },
  },

  /* ── Техника ── */
  {
    id: '23',
    name: 'Скотч прозрачный BRAUBERG, 19 мм×20 м',
    slug: 'tape-brauberg-19-20',
    price: 0.55,
    brand: 'BRAUBERG',
    sku: 'BB-TAPE-19-20',
    categoryId: '11',
    categoryName: 'Техника и картриджи',
    images: ['/images/placeholder-product.svg'],
    rating: 4.2,
    reviewCount: 380,
    stock: 3200,
    badges: [],
    description: 'Прозрачная клейкая лента на пластиковом диспенсере. Высокая клейкость, не желтеет.',
    specs: { 'Ширина': '19 мм', 'Длина': '20 м', 'Материал': 'БОПП' },
  },
]

export const PROMO_SLIDES: PromoSlide[] = [
  {
    id: 1,
    heading: 'Собрался в школу — собрал и сэкономил',
    subheading: 'Готовые наборы первоклассника от 49 руб.',
    cta: 'Собрать набор',
    ctaHref: '/catalog/notebooks',
    bgFrom: '#1e3ab8',
    bgTo: '#2B4DD6',
    emoji: '🎒',
  },
  {
    id: 2,
    heading: 'Ручки BRAUBERG −30%',
    subheading: 'Только до конца недели на всю серию SOFT TOUCH',
    cta: 'Купить со скидкой',
    ctaHref: '/catalog/pens-pencils',
    bgFrom: '#e67722',
    bgTo: '#FF8A3D',
    emoji: '✏️',
  },
  {
    id: 3,
    heading: 'Краски и кисти −20%',
    subheading: 'Художественные материалы для всех уровней',
    cta: 'Смотреть подборку',
    ctaHref: '/catalog/paints-brushes',
    bgFrom: '#5bbba6',
    bgTo: '#7DD3C0',
    emoji: '🎨',
  },
  {
    id: 4,
    heading: 'Бесплатная доставка от 50 руб.',
    subheading: 'По Минску — в день заказа',
    cta: 'Подробнее',
    ctaHref: '/delivery',
    bgFrom: '#0f1d6b',
    bgTo: '#1e3ab8',
    emoji: '📦',
  },
  {
    id: 5,
    heading: 'Опт для офисов: договорная цена',
    subheading: 'Персональный менеджер + рассрочка',
    cta: 'Оставить заявку',
    ctaHref: '/wholesale',
    bgFrom: '#1A1F36',
    bgTo: '#2B4DD6',
    emoji: '🏢',
  },
]

export const FAQ_ITEMS: FAQ[] = [
  {
    question: 'Как оформить заказ?',
    answer: 'Выберите товары через каталог или поиск, добавьте в корзину, заполните контактные данные и удобный способ доставки. Заказ можно оформить круглосуточно — оператор подтвердит его в рабочие часы.',
  },
  {
    question: 'Какие сроки доставки?',
    answer: 'По Минску — в течение 24 часов с момента подтверждения. По Беларуси — 1–3 рабочих дня. Возможен самовывоз из нашего магазина без ожидания.',
  },
  {
    question: 'Можно ли купить оптом и какие условия?',
    answer: 'Да! Оптовые цены доступны от 1 единицы товара — мы не требуем закупать коробками. Для постоянных клиентов — индивидуальные скидки и постоплата. Оставьте заявку — менеджер подготовит коммерческое предложение.',
  },
  {
    question: 'Как оплатить заказ?',
    answer: 'Банковской картой онлайн (Visa, MasterCard, Белкарт), наличными курьеру при получении, по счёту для юридических лиц, в рассрочку (Халва, Магнит).',
  },
  {
    question: 'Что делать, если товара нет в наличии?',
    answer: 'На сайте отображаются только реальные остатки склада. Если нужная позиция закончилась — нажмите «Сообщить о поступлении», и мы уведомим вас на e-mail, как только товар появится.',
  },
  {
    question: 'Можно ли вернуть товар?',
    answer: 'Да, в течение 14 дней с момента покупки, при условии сохранения товарного вида и упаковки. Возврат осуществляется на банковскую карту или наличными.',
  },
  {
    question: 'Делаете ли вы скидки школам и бюджетным организациям?',
    answer: 'Конечно. Для школ, библиотек и детских садов действует специальная программа лояльности — скидки до 15% и приоритетная отгрузка к 1 сентября.',
  },
  {
    question: 'Можно ли получить чек / ЭСЧФ для бухгалтерии?',
    answer: 'Да. Все необходимые документы (накладная, счёт-фактура, ЭСЧФ) выдаются автоматически при оформлении заказа на юрлицо.',
  },
]