name: Deploy to FastPanel

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run deploy script
        run: |
          ssh -o ServerAliveInterval=60 \
              -o ServerAliveCountMax=10 \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              '/root/deploy-kantsmir.sh'
